# Site settings
title: RSS Feed Hub
description: > # this means to ignore newlines until "baseurl:"
  Curated RSS feeds for AI Insights and Technology News
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rss.tedt.org" # the base hostname & protocol for your site

# Jasper theme settings
name: 'RSS Feed Hub'
logo: # 'assets/images/logo.png' # Uncomment when logo is added
favicon: # 'assets/images/favicon.png' # Uncomment when favicon is added
production_url: https://rss.tedt.org
source_url: https://github.com/yourusername/GitHub-Action-To-Read-Table-and-Convert-to-RSS

# Social URLs
facebook_url:
twitter_url:
instagram_url:
github_url: https://github.com/yourusername/GitHub-Action-To-Read-Table-and-Convert-to-RSS

# Mailchimp newsletter
mailchimp_url:

# Disqus
disqus_identifier:

# Google Analytics
google_analytics:

# Authors
authors:
  ted:
    name: Ted
    display_name: Ted
    avatar: # 'assets/images/avatar.png' # Uncomment when avatar is added
    web: https://rss.tedt.org
    description: "RSS feed curator and automation enthusiast"

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag

# Pagination
paginate: 6
paginate_path: /page:num/

# Exclude from processing
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- enhanced_scraper.py
- scrape_to_rss.py
- monitor.py
- config.py
- requirements.txt
- previous_data.json
- debug_*.html

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Gems
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag

# RSS feeds
rss_feeds:
- name: "Ted Tschopp's AI News"
  url: "/ai_rss_feed.xml"
  description: "Latest AI News and Ratings from Ted Tschopp"
  # Single active AI news feed

- name: "Enterprise Architecture Insights"
  url: "https://api.allorigins.win/get?url=https%3A%2F%2Ffeedmix.novaclic.com%2Fmashup.php%3Fs0%3Dhttps%253A%252F%252Fbizzdesign.com%252Fblog%252Ffeed%26n0%3D%26s1%3Dhttps%253A%252F%252Fblog.opengroup.org%252Ffeed%26n1%3D%26s2%3Dhttps%253A%252F%252Feapj.org%252Ffeed%26n2%3D%26s3%3Dhttps%253A%252F%252Ffeed.infoq.com%252Fenterprise-architecture%26n3%3D%26s4%3Dhttps%253A%252F%252Fwww.architectureandgovernance.com%252Felevating-ea%252Ffeed%252F%26n4%3D%26s5%3Dhttps%253A%252F%252Fwww.forrester.com%252Fblogs%252Fcategory%252Fenterprise-architecture%252Ffeed%252F%26n5%3D%26s6%3Dhttps%253A%252F%252Fwww.leanix.net%252Fen%252Fblog%252Frss.xml%26n6%3D%26k%3D%26t%3D1%26m%3Da%26v%3D1"
  description: "Latest insights on Enterprise Architecture"
  proxy: true

- name: "Aggregated External AI & Tech News"
  url: "/aggregated_external.xml"
  description: "Merged headlines from configured external sources"

- name: "Enterprise Architecture Aggregated News"
  url: "/aggregated_ea.xml"
  description: "Enterprise Architecture multi-source aggregated feed"

# RSS display settings
rss_preview_limit: 5
  # Number of RSS items to show in homepage previews (minimum limit - will show more if last 7 days has more items) (default: 5)
  # Change this value to display more or fewer items on the homepage

# Aggregated external RSS sources (now supports multi-feed list)
aggregated_feeds:
- key: aggregated_external
  enabled: true
  output: "/aggregated_external.xml" # Local output file (served by GitHub Pages)
  title: "Aggregated External AI & Tech News"
  link: "https://rss.tedt.org/aggregated_external.xml"
  description: "Merged headlines from configured external sources"
  max_items: 150
  retention_days: 60 # Days to keep in primary aggregated feed before moving to archive
  source_attribution: title # title|description|none - where to place source domain label
  sources:
  - "https://feeds.arstechnica.com/arstechnica/technology-lab"
  - "https://www.infoworld.com/index.rss"
  - "https://www.techrepublic.com/rssfeeds/articles/"
  - "https://www.zdnet.com/news/rss.xml"
- key: aggregated_ea
  enabled: true
  output: "/aggregated_ea.xml"
  title: "Enterprise Architecture Aggregated News"
  link: "https://rss.tedt.org/aggregated_ea.xml"
  description: "Merged Enterprise Architecture sources"
  max_items: 150
  retention_days: 60
  source_attribution: title
  sources:
  - "https://bizzdesign.com/blog/feed"
  - "https://blog.opengroup.org/feed"
  - "https://eapj.org/feed"
  - "https://feed.infoq.com/enterprise-architecture"
  - "https://www.architectureandgovernance.com/elevating-ea/feed/"
  - "https://www.forrester.com/blogs/category/enterprise-architecture/feed/"
  - "https://www.leanix.net/en/blog/rss.xml"
